### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by dsyme** [gregoryyoung/nothing#8]
I'm looking for ways to contribute to this project and thought setting up a CI server for it might be the best place to start.

What should we use for CI on this one?  Is Travis enough?  I'm OK with setting up a dedicated Jenkins server if people think we'll need the throughput.

I assume this needs to be built and tested cross-platform too.

**Comment by gregoryyoung** [comment]
Travis all setup.

It only takes 2 minutes to go through and handle the build how great is that!

https://travis-ci.org/gregoryyoung/nothing
